version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always # always restart on fail
    build: .
    ports:
      - '80:4000'
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis